Repository SoftStackFactory/reboot, pull requests merged in 2018-10, with the labels that each got.

#55 47 dashboard responsiveness
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/dashboard.scss
  src/pages/dashboard/dashboard.ts
Labels: code review

#56 53 transition adding chart
  package-lock.json
  package.json
  src/pages/dashboard/dashboard.ts
  src/pages/transition/transition.html
  src/pages/transition/transition.scss
  src/pages/transition/transition.ts
Labels: code review

#57 51 Dashboard Chart Labels
  src/pages/dashboard/dashboard.ts
Labels: code review

#58 48 login header bar
  src/pages/login/login.html
Labels: code review

#59 46 login responsive
  src/pages/login/login.html
  src/pages/login/login.scss
  src/pages/timeline/timeline.html
  src/pages/timeline/timeline.ts
Labels: code review

#60 54 timeline accordion checkboxes
  src/pages/timeline/timeline.html
  src/pages/timeline/timeline.ts
Labels: code review

#61 41 wizard lanscape/portrait
  src/pages/register/register.html
  src/pages/wizard/wizard.html
  src/pages/wizard/wizard.scss
  src/pages/wizard/wizard.ts
Labels: code review

#62 35 register validation
  src/pages/register/register.html
  src/pages/register/register.scss
  src/pages/register/register.ts
  src/validators/password.validator.ts
Labels: code review

#69 68 transition labels
  src/pages/transition/transition.ts
Labels: code review

#70 35 register validation
  src/pages/register/register.html
  src/pages/register/register.ts
  src/validators/password.validator.ts
Labels: code review

#71 45 profile portrait responsive
  src/pages/profile/profile.html
  src/pages/profile/profile.scss
Labels: code review

#97 Login functionality
  package-lock.json
  package.json
  src/app/app.module.ts
  src/index.html
  src/pages/login/login.html
  src/pages/login/login.scss
  src/pages/login/login.ts
  src/providers/user/user.ts
Labels: code review

#98 49 register layout inconsistencies
  src/pages/register/register.html
  src/pages/register/register.scss
Labels: code review

#100 65 wizard validation error message
  src/app/app.scss
  src/pages/wizard/wizard.html
  src/pages/wizard/wizard.scss
  src/pages/wizard/wizard.ts
  src/theme/variables.scss
Labels: code review, need help

#101 64 timeline component
  src/app/app.module.ts
  src/components/components.module.ts
  src/components/timeline/timeline.html
  src/components/timeline/timeline.scss
  src/components/timeline/timeline.ts
  src/pages/timeline/timeline.html
  src/pages/timeline/timeline.ts
Labels: code review

#108 Added intros to all categories and put range sliders underneath categ…
  src/pages/transition/transition.html
  src/pages/transition/transition.scss
  src/pages/transition/transition.ts
Labels: code review

#110 103 timeline styling
  src/components/timeline/timeline.scss
Labels: code review

#118 Scale modification for charts
  src/pages/dashboard/dashboard.ts
  src/pages/transition/transition.ts
Labels: code review

#119 111 env userprovider
  src/providers/user/user.ts
Labels: code review

#121 65 wizard-validation-error-message
  src/pages/wizard/wizard.html
  src/pages/wizard/wizard.scss
  src/pages/wizard/wizard.ts
Labels: code review

#124 105 register page render issues
  src/pages/register/register.html
  src/pages/register/register.scss
  src/pages/register/register.ts
Labels: code review

#139 131 wizard form refactor
  src/pages/wizard/wizard.html
  src/pages/wizard/wizard.scss
  src/pages/wizard/wizard.ts
Labels: code review

#123 Chart Comments
  src/pages/dashboard/dashboard.ts
  src/pages/login/login.html
  src/pages/transition/transition.ts
Labels: code review

#143 138-changed-css-proporties-for-font-size
  src/pages/profile/profile.scss
Labels: code review

#145 105 register page render issues
  src/pages/login/login.html
  src/pages/login/login.scss
  src/pages/login/login.ts
  src/pages/register/register.html
  src/pages/register/register.scss
  src/pages/register/register.ts
  src/providers/user/user.ts
Labels: code review

#146 got rid of final step in transition page
  src/pages/transition/transition.ts
Labels: code review

#147 132 timeline styling
  src/assets/imgs/blueline.png
  src/components/timeline/timeline.html
  src/components/timeline/timeline.scss
  src/components/timeline/timeline.ts
Labels: code review

#162 151 wizard page view enhancements
  src/app/app.scss
  src/pages/wizard/wizard.html
  src/pages/wizard/wizard.scss
  src/pages/wizard/wizard.ts
Labels: code review

#163 157 chart component
  src/app/app.module.ts
  src/components/chart/chart.html
  src/components/chart/chart.scss
  src/components/chart/chart.ts
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/dashboard.scss
  src/pages/dashboard/dashboard.ts
  src/pages/transition/transition.html
  src/pages/transition/transition.ts
  src/providers/chart/chart.ts
Labels: code review

#164 148 range pinsize
  src/pages/transition/transition.scss
  src/theme/variables.scss
Labels: code review

#167 added special characters to register password validator
  src/pages/login/login.html
  src/pages/register/register.html
  src/pages/register/register.ts
Labels: code review

#176 154-updated branch; new pull request for profile page update without packages
  src/pages/profile/profile.html
  src/pages/profile/profile.scss
Labels: code review

#170 #169 wizard page bug
  src/pages/wizard/wizard.html
  src/pages/wizard/wizard.scss
Labels: code review, need help

#174 152 timeline content
  src/components/timeline/timeline.html
  src/components/timeline/timeline.scss
  src/components/timeline/timeline.ts
  src/pages/timeline/timeline.html
  src/pages/timeline/timeline.scss
Labels: code review

#173 171 wizard page questions modification
  src/pages/wizard/wizard.html
  src/pages/wizard/wizard.ts
Labels: code review

#185 #184-fixed bug by deleting multiple elements
  src/pages/wizard/wizard.html
Labels: code review, enhancement

#178 175 history page
  src/app/app.component.ts
  src/app/app.module.ts
  src/components/chart/chart.ts
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/dashboard.ts
  src/pages/history/history.html
  src/pages/history/history.module.ts
  src/pages/history/history.scss
  src/pages/history/history.ts
  src/pages/login/login.ts
  src/pages/transition/transition.html
  src/pages/transition/transition.ts
  src/providers/chart/chart.ts
Labels: code review

#179 got rid of assessment page in the menu
  src/app/app.component.ts
Labels: code review

#186 180 patch user data
  src/pages/login/login.ts
  src/pages/wizard/wizard.ts
  src/providers/user/user.ts
Labels: code review

#188 158 login register user data
  config.xml
  package.json
  src/app/app.module.ts
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/dashboard.ts
  src/pages/login/login.scss
  src/pages/login/login.ts
  src/pages/register/register.ts
  src/pages/transition/transition.ts
  src/providers/chart/chart.ts
  src/providers/user/user.ts
  src/theme/variables.scss
Labels: code review

#189 Dev
  config.xml
  package-lock.json
  package.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/app.scss
  src/components/chart/chart.html
  src/components/chart/chart.scss
  src/components/chart/chart.ts
  src/components/timeline/timeline.html
  src/components/timeline/timeline.scss
  src/components/timeline/timeline.ts
  src/pages/dashboard/dashboard.html
  src/pages/dashboard/dashboard.scss
  src/pages/dashboard/dashboard.ts
  src/pages/history/history.html
  src/pages/history/history.module.ts
  src/pages/history/history.scss
  src/pages/history/history.ts
  src/pages/login/login.html
  src/pages/login/login.scss
  src/pages/login/login.ts
  src/pages/profile/profile.html
  src/pages/profile/profile.scss
  src/pages/register/register.html
  src/pages/register/register.ts
  src/pages/timeline/timeline.html
  src/pages/timeline/timeline.scss
  src/pages/transition/transition.html
  src/pages/transition/transition.scss
  src/pages/transition/transition.ts
  src/pages/wizard/wizard.html
  src/pages/wizard/wizard.scss
  src/pages/wizard/wizard.ts
  src/providers/chart/chart.ts
  src/providers/user/user.ts
  src/theme/variables.scss
Labels: code review

#187 181-logout-feature
  src/pages/profile/profile.html
  src/pages/profile/profile.ts
  src/providers/user/user.ts
Labels: code review

#192 192 deleted a whole question and update variables
  src/pages/wizard/wizard.html
  src/pages/wizard/wizard.ts
Labels: bug, code review

#193 183 wizard update demo imgs
  src/pages/wizard/wizard.html
  src/pages/wizard/wizard.scss
Labels: code review

#191 Dev
  src/pages/profile/profile.html
  src/pages/profile/profile.ts
  src/pages/wizard/wizard.html
  src/pages/wizard/wizard.scss
  src/pages/wizard/wizard.ts
  src/providers/user/user.ts
Labels: code review, release

#194 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: code review
